server:
  port: 8080

spring:
  application:
    name: web-api
  config:
    import: classpath:application-core.yml

jwt:
  secret: L2Vtc2VjcmV0S2V5Zm9ySE1BQ1NIQTUxMkFsZ29yaXRobS5pbw0KMXNlY3JldEtleWZvckhNQUNDU0hBNTEyQWxnLg==
  accessTokenExpiration: 3600000 # 1 hour in milliseconds
  refreshTokenExpiration: 604800000 # 7 days in milliseconds
